{% set name = "google-cloud-kms" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bedd376807ab3dde08f2d92caa0e4e5ad7c2ccfc7069561e80964b998a0d8f51

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.26.0,<3.0.0dev
    - grpc-google-iam-v1 >=0.12.3,<0.13dev
    - libcst >=0.2.5
    - packaging >=14.3
    - proto-plus >=1.4.0

test:
  imports:
    - google.cloud.kms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-kms
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Cloud Key Management Service (KMS) API client library
  doc_url: https://cloud.google.com/kms/docs/
  dev_url: https://github.com/googleapis/python-kms

extra:
  recipe-maintainers:
    - travisbickle84
    - xylar
