{% set name = "google-cloud-kms" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 0dd5d2215a0814c692d4845be61cbc2e487e13c95e4363e7855001c6c550a6af

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<37]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - google-api-core-grpc >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    - proto-plus >=1.22.3,<2.0.0dev  # [py<=312]
    - proto-plus >=1.25.0,<2.0.0dev  # [py>312]
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    - grpc-google-iam-v1 >=0.12.4,<1.0.0dev

test:
  source_files:
    - tests
  imports:
    - google.cloud.kms
  commands:
    - pip check
    - pytest -v tests/unit
  requires:
    - pip
    - pytest
    - pytest-asyncio

about:
  home: https://github.com/googleapis/python-kms
  summary: Google Cloud Kms API client library
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://cloud.google.com/kms/docs/
  dev_url: https://github.com/googleapis/python-kms

extra:
  recipe-maintainers:
    - travisbickle84
    - xylar
