{% set name = "google-cloud-kms" %}
{% set version = "2.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-kms-{{ version }}.tar.gz
  sha256: eddb1254cf9e552272fc9ab00c7906ccf6f276727cb8be137422694e111b5c6a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.32.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - grpc-google-iam-v1 >=0.12.4,<0.13dev
    - libcst >=0.2.5
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.20.2,<5.0.0dev

test:
  imports:
    - google.cloud.kms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-kms
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Cloud Key Management Service (KMS) API client library
  doc_url: https://cloud.google.com/kms/docs/
  dev_url: https://github.com/googleapis/python-kms

extra:
  recipe-maintainers:
    - travisbickle84
    - xylar
