travis:
  secure:
    BINSTAR_TOKEN: AL/SfJiFzUIWz6cfWkCksCDCIWMl9EZu8RZp0ZtmBSzcYUJ4ivTyLIsW+rCxZxbJCOkoAyqpTPODJM+sYKoKqVmw0gYSiX/hJPvhVga9JB656Kryfy1e27hjjjQkJxUjOYS+w3nifE669Ay+H7+43v0hG3uv7Kz81T2NDrASsDaSIaUXCwPAGrUZnmOLCFziDWLJbp/5HXQVRf37+ufQUJ1by9W7cQjlBPv3lIlBY9Q6mxS48KEoisDMV5ndxC9bu3fA2zsgklokLq1SOgRI6Xa2FrxCozuFh9Q3ApXNB2j8cVV6iGgJtdKgSAhOyoyn7bbxRkjuG8pnABW+69UtbYgG1ZTAMXumWEi7R/1vRI1WScPL4FBbl5sTS2asvC0sGqHcV32ALR41i+C61CyOBxMBehS7hdicb57tFjKCjZRnIMqzex8fn0gSwRL2eG03vSzWzli+QS/sB3pUXw+lweF1fjzVVQlN/UptiwTfGp18R8Vz7WLCVFRK0GC/6SF0ElvV79EoMatJe4UHFGtkOcTu6fp/ekFSKksmJVo5Remt7PuLZ5EdgmWK3NYzCgm/WpEc912E8BIe4xo8PXPjXECyF00oOqJ3Pb2GuuabnP1WByx/3e3HAXg/GgRxaczk+AmP5CzVRF9z8Ft3MQaMtn0MV5NVuZ+MXaRMEMAfpJI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
